### ISSUE TITLE
article submission to hackernoon

### ISSUE THREAD

**Issue by atherdon** [enkiv2/misc#3]
Hi John, nice to meet you.
I'm an editor @ hackernoon.com I saw that you send your story("The Bystander Effect in Open Source") to our publication on medium.

But Hackernoon migrated away from Medium CMS. And I'll be happy to publish your story at Hackernoon 2.0 Tell me what do you think about it?
Will be happy to help.

The fastest way to publish on Hacker Noon is to visit https://HackerNoon.com. 

Learn more about your options publishing with us @ https://contribute.hackernoon.com/

it will be cool if we republish your content and share with our readers. for sure, typing at the new editor can be time-consuming. If you want - I can help you to republish your old stories.

Thanks,
Arthur

**Comment by enkiv2** [comment]
Hey Arthur,
I think you guys already have my previously-submitted stuff syndicated. I
didn't really notice that you stopped accepting new submissions through
medium (though I noticed that you weren't using their CMS anymore). You're
welcome to syndicate that, & anything else I've published on medium that
fits your editorial needs. I probably will not submit new stuff to your
publication because I have existing medium readership.
